name: Unit Tests

on: [push]

jobs:
  build:
    runs-on: [self-hosted, linux, x64]

    steps:
      - uses: actions/checkout@v3
      - name: Cache node_modules
        uses: hashbite/github-action-cache-local-fs@main
        id: node_modules
        env:
          cache-name: node_modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ needs.context.outputs.branch }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-${{ needs.context.outputs.branch }}-
            ${{ runner.os }}-${{ env.cache-name }}-main

      # Install
      - name: Install dependencies via yarn
        run: yarn install --prefer-offline --frozen-lockfile

      # Run unit tests
      - name: Run tests
        run: yarn test
